development:
  adapter: postgresql
  database: db/plantnanny-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/plantnanny-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/plantnanny-production
  pool: 5
  timeout: 5000
