development:
  adapter: postgresql
  database: db/dailydoc-development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/dailydoc-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/dailydoc-production
  pool: 5
  timeout: 5000
